#!/bin/sh

set -e

if [ "$1" == "" ]; then
    echo "please use as 'aws-mfa XXXXXX[6-digit-number] (default region)'"
    exit
else
    mfa=$1
fi
if [ "$2" != "" ]; then
    region=$2
else
    region="ap-northeast-1"
fi

cmd="aws sts get-session-token"
cmd="$cmd --serial-number arn:aws:iam::111111111111:mfa/UserName"
cmd="$cmd --token-code $mfa"

creds=`$cmd`

access_key_id=$(echo $creds | jq --raw-output .Credentials.AccessKeyId)
secret_access_key=$(echo $creds | jq --raw-output .Credentials.SecretAccessKey)
session_token=$(echo $creds | jq --raw-output .Credentials.SessionToken)

aws configure set region $region --profile mfa
aws configure set aws_access_key_id $access_key_id --profile mfa
aws configure set aws_secret_access_key $secret_access_key --profile mfa
aws configure set aws_session_token $session_token --profile mfa

aws configure list --profile mfa
