#!/bin/sh

set -e

if [ "$1" != "" ]; then
  account=$1
else
  account="000000000000"
fi
if [ "$2" != "" ]; then
  region=$2
else
  region="ap-northeast-1"
fi
if [ "$3" != "" ]; then
  profile=$3
else
  profile="RoleName"
fi

echo "account = $account"
echo "region = $region"

cmd="aws sts assume-role"
cmd="$cmd --role-arn arn:aws:iam::${account}:role/$profile"
cmd="$cmd --role-session-name UserName"

creds=`$cmd`

access_key_id=$(echo $creds | jq --raw-output .Credentials.AccessKeyId)
secret_access_key=$(echo $creds | jq --raw-output .Credentials.SecretAccessKey)
session_token=$(echo $creds | jq --raw-output .Credentials.SessionToken)

aws configure set region $region --profile $profile
aws configure set aws_access_key_id $access_key_id --profile $profile
aws configure set aws_secret_access_key $secret_access_key --profile $profile
aws configure set aws_session_token $session_token --profile $profile

aws configure list --profile $profile
